import type { GetServerSideProps, NextPage } from 'next'
import { fetchCategories } from '../http'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ICategory, ICollectionResponse } from '../types'
import { AxiosResponse } from 'axios'
import Tabs from '../components/Tabs'

interface IPropsTypes {
  categories: { items: ICategory[] };
}

const Home: NextPage<IPropsTypes> = ({ categories }) => {
  console.log(categories);

  return (
    <div>
      <Head>
        <title>{ }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs categories={categories.items} />

      <main>

        <h1 className="text-5xl font-bold text-primary-dark">
          Welcome to Next.js!
        </h1>
      </main>
    </div>
  )
};

export const getServerSideProps: GetServerSideProps = async () => {
  // fetch Categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories();

  return {
    props: {
      categories: {
        items: categories.data,
      }
    }
  }
}

export default Home
